# Generated by Django 3.2.8 on 2021-10-16 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('f_modificado', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha modificado')),
                ('f_eliminado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha eliminación')),
                ('nombres', models.CharField(max_length=120, verbose_name='Nombres')),
                ('paterno', models.CharField(max_length=80, verbose_name='Apellido Paterno')),
                ('materno', models.CharField(max_length=80, verbose_name='Apellido Materno')),
                ('telefono', models.IntegerField(max_length=9, verbose_name='Teléfono Móvil')),
                ('autorizado', models.BooleanField(verbose_name='Autorizado')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('creado_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('eliminado_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario eliminación')),
                ('modificado_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario modificador')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cli_cliente',
            },
        ),
    ]
